/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TicTacToeModel */

#ifndef _Included_TicTacToeModel
#define _Included_TicTacToeModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     TicTacToeModel
 * Method:    initialiseBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TicTacToeModel_initialiseBoard
  (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    makeMove
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToeModel_makeMove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     TicTacToeModel
 * Method:    checkWin
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToeModel_checkWin
  (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    checkDraw
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToeModel_checkDraw
  (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    resetBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_TicTacToeModel_resetBoard
  (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    isXTurn
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_TicTacToeModel_isXTurn
  (JNIEnv *, jobject);

/*
 * Class:     TicTacToeModel
 * Method:    getBoardValue
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_TicTacToeModel_getBoardValue
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
